<h2>Navigation</h2>
<ul>
    <li>
        <a
            href="/admin"
        >Start</a>
    </li>
    <li>
        <a
            href="/admin/news"
        >News</a>
        <ul>
            <li>
                <a
                    href="/admin/news/add"
                >News hinzufügen</a>
            </li>
        </ul>
    </li>
    <li>
        <a
            href="/admin/event"
        >Events</a>
        <ul>
            <li>
                <a
                    href="/admin/event/add"
                >Event hinzufügen</a>
            </li>
        </ul>
    </li>
    <li>
        <a
            href="/admin/announcement"
        >Pressemitteilungen</a>
        <ul>
            <li>
                <a
                    href="/admin/announcement/add"
                >Pressemitteilung hinzufügen</a>
            </li>
        </ul>
    </li>
    <li>
        <a
            href="/admin/material"
        >Material</a>
        <ul>
            <li>
                <a
                    href="/admin/material/add"
                >Material hinzufügen</a>
            </li>
        </ul>
    </li>
    <li>
        <a
            href="/admin/media-response"
        >Medienresonanz</a>
        <ul>
            <li>
                <a
                    href="/admin/media-response/add"
                >Medienresonanz hinzufügen</a>
            </li>
        </ul>
    </li>
    <li>
        <a
            href="/admin/tag"
        >Tags</a>
        <ul>
            <li>
                <a
                    href="/admin/tag/add"
                >Tag hinzufügen</a>
            </li>
        </ul>
    </li>
    <li class="separator">
        <a
            href="/admin/twitter"
        >Twitter API</a>
        <ul>
            <li>
                <a
                    class="confirm"
                    href="/admin/twitter/delete"
                >Twitter API löschen</a>
            </li>
        </ul>
    </li>
    <li>
        <a
            href="/admin/delicious"
        >Delicious API</a>
        <ul>
            <li>
                <a
                    class="confirm"
                    href="/admin/delicious/delete"
                >Delicious API löschen</a>
            </li>
        </ul>
    </li>
    <li>
        <a
            href="/admin/flickr"
        >Flickr API</a>
        <ul>
            <li>
                <a
                    class="confirm"
                    href="/admin/flickr/delete"
                >Flickr API löschen</a>
            </li>
        </ul>
    </li>
    <li>
        <a
            href="/admin/youtube"
        >Youtube API</a>
        <ul>
            <li>
                <a
                    class="confirm"
                    href="/admin/youtube/delete"
                >Youtube API löschen</a>
            </li>
        </ul>
    </li>
    <li class="separator">
        <a
            href="/admin/user"
        >Nutzer</a>
        <ul>
            <li>
                <a
                    href="/admin/user/add"
                >Nutzer hinzufügen</a>
            </li>
        </ul>
    </li>
</ul>
