<div class="layoutBox wrapper">
    <?php $noticeSystemMessages = $this->systemMessages('notice'); ?>
    <?php if ($noticeSystemMessages) { ?>
        <div class="layoutBox message notice">
            <h2>Hinweis</h2>
            <ul>
                <?php foreach ($noticeSystemMessages as $message) { ?>
                    <li><?php echo $message; ?></li>
                <?php } ?>
            </ul>
        </div>
    <?php } ?>
    
    <?php $errorSystemMessages = $this->systemMessages('error'); ?>
    <?php if ($errorSystemMessages) { ?>
        <div class="layoutBox message error">
            <h2>Fehler</h2>
            <ul>
                <?php foreach ($errorSystemMessages as $message) { ?>
                    <li><?php echo $message; ?></li>
                <?php } ?>
            </ul>
        </div>
    <?php } ?>
    
    <div class="layoutBox main">
        <?php echo $this->layout()->content; ?>
    </div>
</div>
