<?php echo $this->doctype(); ?>
<html>
<head>
    <meta charset="<?php echo $this->getEncoding(); ?>">
    <!-- <meta http-equiv="Content-Type" content="text/html; charset=<?php echo $this->getEncoding(); ?>"></meta> -->
    
    <?php echo $this->headTitle(); ?>
    
    <?php echo $this->headMeta() ?>
    <meta name="author" content="Mirko Bitsch, Patrick Kromeyer, Anne Grubert, Simon Greiner">

    <link rel="stylesheet" type="text/css" media="all" href="/min/g=default-css" />
    <script type="text/javascript" src="/min/g=default-js"></script>
</head>
<body>
    <div id="wrapper">
	<header>
		<img id="logodhbw" src="/media/img/signet.png">
		&nbsp;
		<img id="logommk" src="/media/img/logo.png">
	</header>
	<nav>
		<ul>
            <a href="/">
                <li>Start</li>
            </a>
            <a href="/news" class="<?php echo strpos($_SERVER['REQUEST_URI'], '/news') === 0 ? 'active' : ''; ?>">
                <li>News</li>
            </a>
            <a href="/event" class="<?php echo strpos($_SERVER['REQUEST_URI'], '/event') === 0 ? 'active' : ''; ?>">
                <li>Events</li>
            </a>
            <a href="/press" class="<?php echo strpos($_SERVER['REQUEST_URI'], '/press') === 0 ? 'active' : ''; ?>">
                <li>Presse</li>
            </a>
		</ul>
	</nav>
	<aside id="left">
		<?php
            echo $this->partial('partial/blogs_networks.phtml');
            echo $this->partial('partial/multimedia_bookmarks.phtml');
            echo $this->partial('partial/subscription.phtml');
            echo $this->partial('partial/contact.phtml');
        ?>
	</aside>
	<div id="content">
    	<?php echo $this->layout()->content; ?>
	</div>
    <aside id="right">
        <?php
            echo $this->partial('partial/twitter.phtml');
            echo $this->partial('partial/youtube.phtml');
            echo $this->partial('partial/delicious.phtml');
            echo $this->partial('partial/subscription.phtml');
			echo $this->partial('partial/contact.phtml');
        ?>
    </aside>
    <hr id="clear">
    <footer>
        <p>
            <a href="/rss">RSS-Feed</a> |
            <a href="/innovator">Die Erfinder</a>
            <span class="right"><a href="/legal">Impressum</a></span>
        </p>
    </footer>
    </div>

    <?php
        if (APPLICATION_ENV === 'production')
        {
            echo $this->partial('partial/google-analytics.phtml');
        }
    ?>
</body>
</html>
