<h1>Die Erfinder - Das N-Team im Gespräch</h1>
<img src="/media/img/inventors.jpg" alt="Die Erfinder">
<p>Der Newsroom ist fertig, doch die Macher kennt kaum einer. Also hat sich das N-Team mal zusammengesetzt und sich selbst interviewt. Lest selbst, was passiert, wenn man anfängt über sich selbst zu reden.</p>

<h2>Was bedeutet der Name N-Team?</h2>
<cite>Der Typograf hat beim M einen Strich vergessen. Es sollte M (mirko) Team heißen. <span class="author minor">Mirko</span></cite>
<cite>Also ich dachte immer es heißt Niemalsbesigbaresundunschlagbaressowieübermenschliches-TEAM :D<span class="author minor">Simon</span></cite>
<cite>Schon klar, Jungs. ☺ Mal im Ernst. Wir haben uns von Anfang an als Team gesehen und auch so bezeichnet. Unser Name ist eine Anspielung auf das unschlagbare A-Team. Das 'N' steht bei uns für Newsroom.<span class="author minor">Anne</span></cite>
<cite>Anne ist nichts hinzuzufügen. Und sollten sie einmal Hilfe benötigen, so rufen Sie doch das N-Team! ;)<span class="author minor">Päd</span></cite>

<h2>Warum habt Ihr euch als Superhelden inszeniert?</h2>
<cite>Als Superhelden inszeniert? Wir sind Superhelden!<span class="author minor">Mirko</span></cite>
<cite>psssssssssst, das darf doch eigentlich keiner wissen :-P<span class="author minor">Simon</span></cite>

<h2>Was war die beste Situation während des Projekts?</h2>
<cite>Als wir in den Zwischenpräsentationen unsere erreichten Ziele zeigen und die Erwartungen meist voll erfüllen konnten.<span class="author minor">Patrick</span></cite>
<cite>Definitiv das Fotoshooting, dass wir hatten. Das war echt der Hammer.<span class="author minor">Anne</span></cite>
<cite>Als die Mobile-Seite zum erstmal halbwegs richtig angezeigt wurde!<span class="author minor">Mirko</span></cite>
<cite>Mit Sicherheit auch das Fotoshooting ‚dass war echt seeehr lustig :-)<span class="author minor">Simon</span></cite>

<h2>Ihr habt nicht viel geschlafen in der Projektzeit. Hat euch das verändert?</h2>
<cite>zzzZZZZzzzZZZZ<span class="author minor">Mirko</span></cite>
<cite>Ja, wir sind jetzt noch verrückter als ohnehin schon. Aber auf ne gute Art‚ ... denke ich.<span class="author minor">Anne</span></cite>

<h2>Seid ihr typische Computer-Nerds?</h2>
<cite>Ja, aber ohne die gesunde Kellerbräune!<span class="author minor">Päd</span></cite>
<cite>Nein, aber mit der gesunden Kellerbräune!<span class="author minor">Mirko</span></cite>
<cite>ja, nein, doch...ich glaub irgendwie schon<span class="author minor">Anne</span></cite>
<cite>Nerds ? Sehn wir so aus ??? Digital Natives ist das Stichwort :-P<span class="author minor">Simon</span></cite>

<h2>Eine Letzte Frag: was macht Ihr so, wenn ihr nicht grad Dr. NoRoom jagt?</h2>
<cite>Ich bin beim Adolf Christ Verlag in Frankfurt am Main angestellt und arbeite hauptsächlich in der Marketing-Abteilung. Kreative Ideen, Konzeption, und Texte verfassen gehören zu meinen täglichen Aufgaben. Vor dem Studium habe ich eine Ausbildung zur Mediengestalterin gemacht und später als Grafikerin gearbeitet. Ihr wollt wissen warum ich studiere? Ich wollte mehr von der Welt sehen und nicht nur Pixel schubsen, auch wenn ich diesen Job sehr liebe.<span class="author minor">Anne</span></cite>
<cite>Als Webentwickler bei der CAMAO AG in Darmstadt beschäftige ich mich während meiner Praxisphase täglich mit den Werkzeugen und der Umsetzung moderner und qualitativ hochwertiger Webanwendungen. Es macht einfach Spaß, wenn man sieht, wie die eigenen Projekte Flügel bekommen und dann auch abheben.<span class="author minor">Päd</span></cite>
<cite>Ich arbeite bei der Dr. Jung Group in München. Zuvor habe ich eine Ausbildung als Mediengestalter beim Springer Verlag HD gemacht. Warum ich weiter studiere? Die Ausbildung war mir zu flach!<span class="author minor">Mirko</span></cite>
<cite>Ich arbeite auch bei der Dr. Jung Group und bin dort vorwiegend in der Kundenberatung tätig. In diesem Bereich lerne ich täglich, was es heißt kreative Werbekonzepte für Pharmaunternehmen zu erstellen und die Kunden während des gesamten Projektes, das Mailings, Emailkampagnen oder auch Kampagnen direkt beim Arzt beinhaltet, bestmöglich zu betreuen. Des Weiteren kann ich in vielen weiteren Bereichen, wie der Buchhaltung, der Eventabteilung oder der Produktion, immer mal ein Blick über die Schulter werfen, oder auch mal mit 'anpacken'.<span class="author minor">Simon</span></cite>
