<h1>Impressum</h1>

<h2>Studiengang Medienmanagement und Kommunikation</h2>
<p>
    Duale Hochschule Baden-Württemberg Mannheim<br>
    Coblitzallee 1-9<br>
    68163 Mannheim<br>
    Studiengang Medienmanagement und Kommunikation
</p>

<h2>Leitung</h2>
<p>
    Prof. Dr. Gerald Lembke<br>
    <a href="mailto:gerald.lembke@dhbw-mannheim.de">gerald.lembke@dhbw-mannheim.de</a><br>
    Tel. 0621 4105-1304<br>
    Fax 0621 4105-1245
</p>

<h2>Sekretariat</h2>
<p>
    Márcia Feyh-Hilberer<br>
    <a href="mailto:marcia.feyh-hilberer@dhbw-mannheim.de">marcia.feyh-hilberer@dhbw-mannheim.de</a><br>
    Tel. 0621 4105-1152<br>
    Fax 0621 4105-1245
</p>

<h2>Rechtsform</h2>
<p>
    Die Duale Hochschule Baden-Württemberg ist nach § 1 Abs. 1 DH-ErrichtG vom 12.12.2008 eine rechtsfähige Körperschaft des öffentlichen Rechts und zugleich staatliche Einrichtung.
</p>
<p>
    Die Duale Hochschule Baden-Württemberg Mannheim ist nach § 1 Abs. 2 DH-ErrichtG vom 12.12.2008 eine rechtlich unselbständige Untereinheit dieser Hochschule.
</p>

<h2>Zuständige Aufsichtsbehörde</h2>
<p>
    Duale Hochschule Baden-Württemberg<br>
    Gesetzlich vertreten durch den Präsidenten der Dualen Hochschule Baden-Württemberg<br>
    Professor Reinhold R. Geilsdörfer<br>
    Friedrichstraße 14<br>
    70174 Stuttgart<br>
    Tel. 0711 320 660-0<br>
    Fax 0711 320 660-66<br>
    <a href="mailto:poststelle@dhbw.de">poststelle@dhbw.de</a><br>
    <a href="http://www.dhbw.de">www.dhbw.de</a>
</p>
<p>
    Die Duale Hochschule Baden-Württemberg ist eine rechtsfähige Körperschaft des öffentlichen Rechts.
</p>
<p>
    Umsatzsteuer-Identifikationsnummer gemäß § 27 a Umsatzsteuergesetz: DE 811498218
</p>

<h2>Webserver-Administration</h2>
<p>
    Duale Hochschule Baden-Württemberg Mannheim
</p>

<h2>Haftungsausschluss</h2>
<p>
    Die Inhalte dieser Seiten wurden mit größter Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte können wir jedoch keine Gewähr übernehmen. Die Duale Hochschule Baden-Württemberg behält sich das Recht vor, ohne vorherige Ankündigung, Änderungen oder Ergänzungen der bereitgestellten Informationen vorzunehmen.
</p>
<p>
    Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei bekannt werden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.
</p>
<p>
    Die Duale Hochschule Baden-Württemberg begründet durch die Bereitstellung dieser Informationen kein Vertragsangebot über Auskünfte, Beratung oder ähnliche Vertragsbeziehungen. Jegliche Haftung für die Nutzung der Inhalte der Web Site oder die Richtigkeit der Inhalte oder die Erreichbarkeit der Web Site wird ausgeschlossen. Die Duale Hochschule Baden-Württemberg haftet daher nicht für konkrete, mittelbare und unmittelbare Schäden oder Schäden, die durch fehlende Nutzungsmöglichkeiten, Datenverluste oder entgangene Gewinne entstehen können, die im Zusammenhang mit der Nutzung von Dokumenten oder Informationen entstehen, die auf dieser Web Site zugänglich sind.
</p>

<h2>Urheberrecht</h2>
<p>
    Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Beiträge Dritter sind als solche gekennzeichnet.
</p>
<p>
    Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.
</p>

<h2>Datenschutz</h2>
<p>
    Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, Anschrift oder E-Mail-Adressen) erhoben werden, erfolgt dies soweit möglich stets auf freiwilliger Basis. Die Nutzung der Angebote und Dienste ist, soweit möglich, stets ohne Angabe personenbezogener Daten möglich.
</p>
<p>
    Der Nutzung von auf dieser Website veröffentlichten Kontaktdaten durch Dritte zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit ausdrücklich widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails, vor.
</p>
