<section class="contact start">
	<h1>Kontakt</h1>
	<div id="hcard-Marcia-Feyh-Hilberer" class="vcard box">
	  <img style="float:left" src="http://www.mm.dhbw-mannheim.de/uploads/pics/tl-sh-mm-fhm-sw-1543.jpg" alt="photo of Marcia Feyh-Hilberer" class="photo"/>
	 <a class="url fn" href="http://www.mm.dhbw-mannheim.de/">Marcia Feyh-Hilberer</a>
	 <div class="org">DHBW-Mannheim MMK</div>
	 <a class="email" href="mailto:marcia.feyh-hilberer@dhbw-mannheim.de">marcia.feyh-hilberer@dhbw-mannheim.de</a>
	 <div class="adr">
	  <div class="street-address">Coblitzallee 1-9</div>
	  <span class="locality">Mannheim</span>
	, 
	  <span class="region">Baden-Württemberg</span>
	, 
	  <span class="postal-code">68163</span>

	  <span class="country-name">Deutschland</span>

	 </div>
	  <div class="mail">via <a href="mailto:marcia.feyh-hilberer@dhbw-mannheim.de">E-Mail</a></div>
	  <div class="facebook">via <a href="http://www.facebook.com/Marcia.feyh.hilberer">facebook</a></div>
      <div class="xing">via <a href="https://www.xing.com/profile/Marcia_FeyhHilberer">xing</a></div>
	  <div class="tel">(0621) 4105-1152</div>
	</div>
</section>