<div class="element <?php echo $this->element->getAttrib('class') ? $this->element->getAttrib('class') : ''; ?>">
    <?php
        echo $this->formLabel(
                $this->element->getName(),
                $this->element->getLabel()
        );
    ?>

    <div class="element-wrapper">
        <?php
            switch ($this->element->helper)
            {
                case 'formRadio':
                case 'formSelect':
                    echo $this->{$this->element->helper}(
                        $this->element->getName(),
                        $this->element->getValue(),
                        $this->element->getAttribs(),
                        $this->element->getMultiOptions()
                    );
                    break;
                case 'formCheckbox':
                    echo $this->{$this->element->helper}(
                        $this->element->getName(),
                        $this->element->getValue(),
                        $this->element->getAttribs(),
                        array(
                            'checkedValue' => $this->element->getCheckedValue(),
                            'uncheckedValue' => $this->element->getUncheckedValue()
                        )
                    );
                    break;
                default:
                    echo $this->{$this->element->helper}(
                        $this->element->getName(),
                        $this->element->getValue(),
                        $this->element->getAttribs()
                    );
            }
        ?>
    </div>

    <?php
        if (count($this->element->getMessages()))
        {
            echo $this->formErrors(
                $this->element->getMessages()
            );
        }

        if ($this->element->getDescription())
        {
    ?>
        <p><?php echo $this->element->getDescription(); ?></p>
    <?php } ?>
</div>
