<article>
	<p>Medienmanagement und Kommunikation ist ein dualer Studiengang an der DHBW Mannheim. Er bereitet Studierende und Unternehmen auf die zunehmende Digitalisierung vor. Dazu gehören Fertigkeiten und Fähigkeiten in der Analyse, Konzeption, Gestaltung und Produktion von innovativen Medienstrategien und digitalen Services und Produkten. Betriebswirtschaftliche Analysen, aktuellste Medientechnologien sowie die Anwendung und die kritische Auseinandersetzung stehen dabei im Zentrum dieses Hochschulstudiums.</p>

	<p>Weiterführende Informationen finden Sie unter <a href="http://www.medienmanagement.info">http://www.medienmanagement.info</a></p>
</article>