<section class="blogs_networks social">
	<h1>Blogs & Networks</h1>
	<ul class="box">
		<a href="https://www.facebook.com/Medienmanagement.Kommunikation?sk=app_4949752878">
			<li class="facebook">Facebook</li>
		</a>
		<a href="http://www.twitter.com/medienmanagen">
			<li class="twitter">Twitter</li>
		</a>
		<a href="http://www.schuelervz.net/Groups/Overview/e51cb00c22a1ee50">
			<li class="vz">VZ-Gruppe</li>
		</a>
		<a href="http://www.xing.com/net/mmk/">
			<li class="xing">Xing-Gruppe</li>
		</a>
	</ul>
</section>