<section class="multimedie_bookmarks social">
	<h1>Multimedia & Bookmarks</h1>
	<ul class="box">
		<a href="http://www.youtube.com/user/Medienmanagement">
			<li class="youtube">Video</li>
		</a>
		<a href="http://www.flickr.com/photos/medienmanagement/">
			<li class="flickr">Foto</li>
		</a>
		<a href="http://www.slideshare.net/medienmanagement">
			<li class="slideshare">Dokument</li>
		</a>
		<a href="http://www.delicious.com/mmk/">
			<li class="delicious">Lesezeichen</li>
		</a>
	</ul>
</section>