<tr>
    <td><?php echo $this->escape($this->object->headline); ?></td>
    <td><?php echo $this->object->date; ?></td>
    <td><?php echo $this->object->time; ?> Uhr</td>
    <td>
        <ul>
            <li>
                <a
                    href="/admin/event/comment/<?php echo $this->object->id; ?>"
                >Kommentare</a>
            </li>
            <li>
                <a
                    href="/admin/event/edit/<?php echo $this->object->id; ?>"
                >Bearbeiten</a>
            </li>
            <li>
                <a
                    class="confirm"
                    href="/admin/event/delete/<?php echo $this->object->id; ?>"
                >Löschen</a>
            </li>
        </ul>
    </td>
</tr>
