<tr>
    <td><?php echo $this->escape($this->object->title); ?></td>
    <td>
        <ul>
            <li>
                <a
                    href="/admin/media-response/edit/<?php echo $this->object->id; ?>"
                >Bearbeiten</a>
            </li>
            <li>
                <a
                    class="confirm"
                    href="/admin/media-response/delete/<?php echo $this->object->id; ?>"
                >Löschen</a>
            </li>
        </ul>
    </td>
</tr>
